# Generated by Django 5.1.2 on 2024-10-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
